pull request #1 from techmoves/htmlcss-branch
techmoves/hello-microverse pull request #3
Opened 2023-02-14 21:25 UTC by techmoves

hello microverse pull request
sorry it was merge by mistake

2023-02-14 21:51 UTC, AbayomiOlaoye requested changes
## STATUS: CHANGE REQUIRED ♻️ 

Hi @techmoves  :wave: 

Good job with this milestone so far!
There are just a few more issues to work on before moving on to the next project but you are almost there!

![so_close](https://user-images.githubusercontent.com/99715640/211950260-0e3881c0-9d4f-4ea2-a670-9ef45a23a0f5.gif)

## Highlights
- Descriptive Pull Request message :heavy_check_mark: 
- Good use of GitHub flow :heavy_check_mark: 
- Meaningful commit messages :heavy_check_mark: 
- No linter error :heavy_check_mark: 
- Good implementation :heavy_check_mark: 

## Required Changes ♻️
- Sorry about the mistake, it happens. I have checked your code and all but the README seems well.
- [ ] :+1: You have made a brilliant effort to get this up and running you still need to give your nice README.md some more time and attention so that you can have content that make your project looks professional to visitors or users. Kindly check [this README template](https://github.com/microverseinc/readme-template) again and see all the important sub-titles that you are missing and their respective details.
  - [ ] * The only **optional** section is FAQ.
  * You can delete the live demo section since you are not deploying your application now.
  * Kindly add the section **Future Features**, including 1-3 potential features to be added.
* It will be more customized to **remove the section description**, i.e. "> Describe the tech stack and include only the relevant sections that apply to your project." should be removed and filled in with their custom content.
**NB**: Please pay attention to the table of contents how they serve as hyperlinks redirecting to specific sections of the `README`, and try to apply it to yours too. It makes your Readme more accessible and eases navigation. :+1: 

## Optional suggestions
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-15 08:35 UTC, mahbubul14 requested changes
Hi @techmoves,

Great work on making the changes requested by the previous reviewer 👏

You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

# Required Changes ♻️

- [ ] The titles and sub-titles of the readme section should be highlighted well and kindly make text linkable where needed(ex: authors, MIT licensed). It would be better if you remove microverse logo from the heading of the readme file as well.
 
###  To Highlights
:heavy_check_mark: No linter error.
:heavy_check_mark: Proper Github flow used.
:heavy_check_mark: Descriptive PR title & description.

### Optional suggestions

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

* N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also reach me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-02-15 09:13 UTC, AlphaNtihinduka reviewed
Hi @techmoves ,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌ 

It seems that he could have submitted a PR for the wrong milestone. Kindly verify the PR and make new request for the correct milestone.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready pray

Cheers and Happy coding 👏 👏 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

2023-02-15 20:14 UTC, divinecharlotte requested changes
Hi @techmoves 👋, 

## STATUS: REQUESTED CHANGES ♻️ 

Good job so far 👏 
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media3.giphy.com/media/h7u3pLvYK3HfQ4yXxW/giphy.gif"/>

### To Highlight 🎯 💡 


## Required Changes ♻️
_Check the comments under the review._


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-15 20:14 UTC, divinecharlotte commented on README.md
> +</div>
- [ ] Kindly consider removing this microverse logo or add yours if you have any cause  this will make your repo personal.

2023-02-15 20:14 UTC, divinecharlotte commented on README.md
> +# 📖 [Hello microverse] <a name="about-project"></a>
- [ ] consider removing the brackets on this title to make it look good

2023-02-15 20:14 UTC, divinecharlotte commented on README.md
> +**[Hello hello microverse]**
- [ ] consider removing this too avoid unwanted informations

2023-02-15 20:14 UTC, divinecharlotte commented on README.md
> +**[Hello hello microverse]**
- [ ] consider removing this too avoid unwanted informations

2023-02-15 20:14 UTC, divinecharlotte commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
- [ ] kindly consider removing this link or note it as N/A as you are not deploying this project to avoid broken links which are not professional

2023-02-15 21:52 UTC, shella12 requested changes
Hi @techmoves , 

Great work on making the changes requested by a previous reviewer 👏 👏 👏 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet. You are almost there...

<img src="https://media1.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights

-  Add more description to the README✅ 

 ## Required Changes ♻️

- [ ] _Check the comments under the review._


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- [ ] [OPTIONAL] While you have made a great 👍 effort to implement all the changes ♻️ suggested by the previous reviewers 🤓, you have been making in the wrong branch 😅. You implemented changes in the main branch whereas you should have used feature branch to implement changes. Please check [How to use GitHub flow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md) to learn how to use correct git-flow. 
Using the correct git-flow is a [requirement](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/hello_microverse_project.md) of the project but for now, I'll request them as [OPTIONAL]. Please make sure that you use correct workflow in the future ☺️ 

<img width="741" alt="Screenshot 2023-02-16 at 2 14 35 AM" src="https://user-images.githubusercontent.com/44798044/219172963-e28d7e1e-a7d4-4ce2-9944-625ad89e5034.png">

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-15 21:52 UTC, shella12 commented on README.md
- [ ] As requested by the previous reviewers please 🙏 remove _`Note:`_ from the LICENCE section of the README. Note 🗒️  is there in the template to guide you on how you to add a LICENCE to your README. Once you have successfully added the LICENCE you can go ahead and remove it 👍

2023-02-15 21:52 UTC, shella12 commented on README.md
> +  - [Answer_1]
- [ ] FAQ section is optional in the project README. Please 🙏 remove it from your README if you don't want put details 😃

2023-02-15 21:52 UTC, shella12 commented on README.md
> +
- [ ] As requested by the previous reviewer please 🙏 remove comments like

> Give credit to everyone who inspired your codebase.

from your README as there purpose is to describe the use of the section from the [template](https://github.com/microverseinc/readme-template). Once you have implemented required changes you can go ahead and remove it 👍

2023-02-15 21:52 UTC, shella12 commented on README.md
> +> to new student    from microverse they veiw this project for review
- [ ] As requested by the previous reviewer please 🙏 remove comments like

> Write a message to encourage readers to support your project to new student from microverse they veiw this project for review

from your README as there purpose is to describe the use of the section from the [template](https://github.com/microverseinc/readme-template). Once you have implemented required changes you can go ahead and remove it 👍

2023-02-15 21:52 UTC, shella12 commented on README.md
> -(back to top)
- [ ] As requested by the previous reviewers, please 🙏 make sure to customize it to reflect your Project

2023-02-15 21:52 UTC, shella12 commented on README.md
> +- [📝 License](#license)
- [ ] While you have made a great effort to include all sections from README [template](https://github.com/microverseinc/readme-template) links to some are broken and some of the sections in the `Table of content` have been deleted from the README. Please make sure to add all sections and their customized detail into the README

2023-02-16 08:25 UTC, closed without merging